project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"   # render everything…
    - "!posts/**"  # …except any files inside posts/
    - "!posts.qmd" # …and the posts index page itself
website:
  title: "Abigail Cassario"
  google-analytics: "G-6L8SFJ66MV"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - Teaching.qmd
      - posts.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
  

