project:
  type: website
  output-dir: docs

website:
  title: "Abigail Cassario"
  google-analytics: "G-6L8SFJ66MV"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - Teaching.qmd
      - posts.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true



